export default () => [
  {
    region: 'Алтайский край',
    district: 'Сибирский федеральный округ',
    district_short: 'СФО',
    region_alt_rus: 'Ал. к.',
    region_eng: 'ALK',
    region_rus: 'АЛТК',
    col: '12',
    row: '5',
  },
  {
    region: 'Амурская область',
    district: 'Дальневосточный федеральный округ',
    district_short: 'ДФО',
    region_alt_rus: 'Амур',
    region_eng: 'AMU',
    region_rus: 'АМУР',
    col: '15',
    row: '3',
  },
  {
    region: 'Архангельская область',
    district: 'Северо-Западный федеральный округ',
    district_short: 'СЗФО',
    region_alt_rus: 'Арх',
    region_eng: 'ARH',
    region_rus: 'АРХ',
    col: '8',
    row: '2',
  },
  {
    region: 'Астраханская область',
    district: 'Южный федеральный округ',
    district_short: 'ЮФО',
    region_alt_rus: 'Аст',
    region_eng: 'AST',
    region_rus: 'АСТ',
    col: '7',
    row: '8',
  },
  {
    region: 'Белгородская область',
    district: 'Центральный федеральный округ',
    district_short: 'ЦФО',
    region_alt_rus: 'Бел',
    region_eng: 'BEL',
    region_rus: 'БЕЛ',
    col: '4',
    row: '7',
  },
  {
    region: 'Брянская область',
    district: 'Центральный федеральный округ',
    district_short: 'ЦФО',
    region_alt_rus: 'Бря',
    region_eng: 'BRN',
    region_rus: 'БРН',
    col: '2',
    row: '5',
  },
  {
    region: 'Владимирская область',
    district: 'Центральный федеральный округ',
    district_short: 'ЦФО',
    region_alt_rus: 'Вла',
    region_eng: 'VLA',
    region_rus: 'ВЛА',
    col: '5',
    row: '4',
  },
  {
    region: 'Волгоградская область',
    district: 'Южный федеральный округ',
    district_short: 'ЮФО',
    region_alt_rus: 'Волг',
    region_eng: 'VGG',
    region_rus: 'ВЛГГ',
    col: '6',
    row: '7',
  },
  {
    region: 'Вологодская область',
    district: 'Северо-Западный федеральный округ',
    district_short: 'СЗФО',
    region_alt_rus: 'Воло',
    region_eng: 'VGD',
    region_rus: 'ВЛГД',
    col: '4',
    row: '2',
  },
  {
    region: 'Воронежская область',
    district: 'Центральный федеральный округ',
    district_short: 'ЦФО',
    region_alt_rus: 'Вор',
    region_eng: 'VRN',
    region_rus: 'ВРН',
    col: '5',
    row: '7',
  },
  {
    region: 'Еврейская автономная область',
    district: 'Дальневосточный федеральный округ',
    district_short: 'ДФО',
    region_alt_rus: 'Евр',
    region_eng: 'YEV',
    region_rus: 'ЕВР',
    col: '15',
    row: '4',
  },
  {
    region: 'Забайкальский край',
    district: 'Сибирский федеральный округ',
    district_short: 'СФО',
    region_alt_rus: 'Заб',
    region_eng: 'ZAB',
    region_rus: 'ЗАБ',
    col: '14',
    row: '5',
  },
  {
    region: 'Ивановская область',
    district: 'Центральный федеральный округ',
    district_short: 'ЦФО',
    region_alt_rus: 'Ива',
    region_eng: 'IVA',
    region_rus: 'ИВА',
    col: '5',
    row: '3',
  },
  {
    region: 'Иркутская область',
    district: 'Сибирский федеральный округ',
    district_short: 'СФО',
    region_alt_rus: 'Ирк',
    region_eng: 'IRK',
    region_rus: 'ИРК',
    col: '14',
    row: '3',
  },
  {
    region: 'Кабардино-Балкарская Республика',
    district: 'Северо-Кавказский федеральный округ',
    district_short: 'СКФО',
    region_alt_rus: 'Каб',
    region_eng: 'KBR',
    region_rus: 'КБР',
    col: '4',
    row: '10',
  },
  {
    region: 'Калининградская область',
    district: 'Северо-Западный федеральный округ',
    district_short: 'СЗФО',
    region_alt_rus: 'Кали',
    region_eng: 'KLN',
    region_rus: 'КЛН',
    col: '0',
    row: '3',
  },
  {
    region: 'Калужская область',
    district: 'Центральный федеральный округ',
    district_short: 'ЦФО',
    region_alt_rus: 'Калу',
    region_eng: 'KLG',
    region_rus: 'КЛЖ',
    col: '3',
    row: '4',
  },
  {
    region: 'Камчатский край',
    district: 'Дальневосточный федеральный округ',
    district_short: 'ДФО',
    region_alt_rus: 'Кам',
    region_eng: 'KAM',
    region_rus: 'КАМ',
    col: '17',
    row: '1',
  },
  {
    region: 'Карачаево-Черкесская Республика',
    district: 'Северо-Кавказский федеральный округ',
    district_short: 'СКФО',
    region_alt_rus: 'Кара',
    region_eng: 'KCH',
    region_rus: 'КЧР',
    col: '4',
    row: '9',
  },
  {
    region: 'Кемеровская область',
    district: 'Сибирский федеральный округ',
    district_short: 'СФО',
    region_alt_rus: 'Кем',
    region_eng: 'KEM',
    region_rus: 'КЕМ',
    col: '13',
    row: '3',
  },
  {
    region: 'Кировская область',
    district: 'Приволжский федеральный округ',
    district_short: 'ПФО',
    region_alt_rus: 'Кир',
    region_eng: 'KIR',
    region_rus: 'КИР',
    col: '8',
    row: '3',
  },
  {
    region: 'Костромская область',
    district: 'Центральный федеральный округ',
    district_short: 'ЦФО',
    region_alt_rus: 'Кос',
    region_eng: 'KOS',
    region_rus: 'КОСТ',
    col: '6',
    row: '3',
  },
  {
    region: 'Краснодарский край',
    district: 'Южный федеральный округ',
    district_short: 'ЮФО',
    region_alt_rus: 'Крдр',
    region_eng: 'KRD',
    region_rus: 'КРНД',
    col: '4',
    row: '8',
  },
  {
    region: 'Красноярский край',
    district: 'Сибирский федеральный округ',
    district_short: 'СФО',
    region_alt_rus: 'Крас',
    region_eng: 'KRN',
    region_rus: 'КРСН',
    col: '13',
    row: '2',
  },
  {
    region: 'Курганская область',
    district: 'Уральский федеральный округ',
    district_short: 'УФО',
    region_alt_rus: 'Кург',
    region_eng: 'KRG',
    region_rus: 'КУРГ',
    col: '11',
    row: '4',
  },
  {
    region: 'Курская область',
    district: 'Центральный федеральный округ',
    district_short: 'ЦФО',
    region_alt_rus: 'Курск',
    region_eng: 'KSK',
    region_rus: 'КРСК',
    col: '3',
    row: '6',
  },
  {
    region: 'Ленинградская область',
    district: 'Северо-Западный федеральный округ',
    district_short: 'СЗФО',
    region_alt_rus: 'Лен',
    region_eng: 'LEN',
    region_rus: 'ЛЕН',
    col: '2',
    row: '2',
  },
  {
    region: 'Липецкая область',
    district: 'Центральный федеральный округ',
    district_short: 'ЦФО',
    region_alt_rus: 'Лип',
    region_eng: 'LIP',
    region_rus: 'ЛИП',
    col: '4',
    row: '6',
  },
  {
    region: 'Магаданская область',
    district: 'Дальневосточный федеральный округ',
    district_short: 'ДФО',
    region_alt_rus: 'Маг',
    region_eng: 'MAG',
    region_rus: 'МАГ',
    col: '16',
    row: '2',
  },
  {
    region: 'Москва',
    district: 'Центральный федеральный округ',
    district_short: 'ЦФО',
    region_alt_rus: 'Мск',
    region_eng: 'MSK',
    region_rus: 'МСК',
    col: '0',
    row: '1',
  },
  {
    region: 'Московская область',
    district: 'Центральный федеральный округ',
    district_short: 'ЦФО',
    region_alt_rus: 'Мос',
    region_eng: 'MOB',
    region_rus: 'МОБЛ',
    col: '4',
    row: '4',
  },
  {
    region: 'Мурманская область',
    district: 'Северо-Западный федеральный округ',
    district_short: 'СЗФО',
    region_alt_rus: 'Мур',
    region_eng: 'MUR',
    region_rus: 'МУР',
    col: '4',
    row: '0',
  },
  {
    region: 'Ненецкий автономный округ',
    district: 'Северо-Западный федеральный округ',
    district_short: 'СЗФО',
    region_alt_rus: 'Нен',
    region_eng: 'NEN',
    region_rus: 'НЕН',
    col: '9',
    row: '1',
  },
  {
    region: 'Нижегородская область',
    district: 'Приволжский федеральный округ',
    district_short: 'ПФО',
    region_alt_rus: 'Ниж',
    region_eng: 'NIZ',
    region_rus: 'НИЖ',
    col: '6',
    row: '4',
  },
  {
    region: 'Новгородская область',
    district: 'Северо-Западный федеральный округ',
    district_short: 'СЗФО',
    region_alt_rus: 'Новг',
    region_eng: 'NVG',
    region_rus: 'НОВГ',
    col: '3',
    row: '2',
  },
  {
    region: 'Новосибирская область',
    district: 'Сибирский федеральный округ',
    district_short: 'СФО',
    region_alt_rus: 'Ново',
    region_eng: 'NSK',
    region_rus: 'НСК',
    col: '12',
    row: '4',
  },
  {
    region: 'Омская область',
    district: 'Сибирский федеральный округ',
    district_short: 'СФО',
    region_alt_rus: 'Омск',
    region_eng: 'OMS',
    region_rus: 'ОМСК',
    col: '11',
    row: '5',
  },
  {
    region: 'Оренбургская область',
    district: 'Приволжский федеральный округ',
    district_short: 'ПФО',
    region_alt_rus: 'Орен',
    region_eng: 'ORE',
    region_rus: 'ОРЕН',
    col: '8',
    row: '6',
  },
  {
    region: 'Орловская область',
    district: 'Центральный федеральный округ',
    district_short: 'ЦФО',
    region_alt_rus: 'Орёл',
    region_eng: 'ORL',
    region_rus: 'ОРЛ',
    col: '3',
    row: '5',
  },
  {
    region: 'Пензенская область',
    district: 'Приволжский федеральный округ',
    district_short: 'ПФО',
    region_alt_rus: 'Пен',
    region_eng: 'PNZ',
    region_rus: 'ПЕНЗ',
    col: '6',
    row: '6',
  },
  {
    region: 'Пермский край',
    district: 'Приволжский федеральный округ',
    district_short: 'ПФО',
    region_alt_rus: 'Пер',
    region_eng: 'PER',
    region_rus: 'ПЕРМ',
    col: '9',
    row: '3',
  },
  {
    region: 'Приморский край',
    district: 'Дальневосточный федеральный округ',
    district_short: 'ДФО',
    region_alt_rus: 'При',
    region_eng: 'PRI',
    region_rus: 'ПРИМ',
    col: '16',
    row: '5',
  },
  {
    region: 'Псковская область',
    district: 'Северо-Западный федеральный округ',
    district_short: 'СЗФО',
    region_alt_rus: 'Пск',
    region_eng: 'PSK',
    region_rus: 'ПСК',
    col: '2',
    row: '3',
  },
  {
    region: 'Республика Адыгея',
    district: 'Южный федеральный округ',
    district_short: 'ЮФО',
    region_alt_rus: 'Адыг',
    region_eng: 'ADG',
    region_rus: 'АДГ',
    col: '3',
    row: '8',
  },
  {
    region: 'Республика Алтай',
    district: 'Сибирский федеральный округ',
    district_short: 'СФО',
    region_alt_rus: 'Алт',
    region_eng: 'ALR',
    region_rus: 'АЛТР',
    col: '12',
    row: '6',
  },
  {
    region: 'Республика Башкортостан',
    district: 'Приволжский федеральный округ',
    district_short: 'ПФО',
    region_alt_rus: 'Бшк',
    region_eng: 'BAS',
    region_rus: 'БАШ',
    col: '9',
    row: '5',
  },
  {
    region: 'Республика Бурятия',
    district: 'Сибирский федеральный округ',
    district_short: 'СФО',
    region_alt_rus: 'Бур',
    region_eng: 'BUR',
    region_rus: 'БУР',
    col: '14',
    row: '4',
  },
  {
    region: 'Республика Дагестан',
    district: 'Северо-Кавказский федеральный округ',
    district_short: 'СКФО',
    region_alt_rus: 'Даг',
    region_eng: 'DAG',
    region_rus: 'ДАГ',
    col: '7',
    row: '9',
  },
  {
    region: 'Республика Ингушетия',
    district: 'Северо-Кавказский федеральный округ',
    district_short: 'СКФО',
    region_alt_rus: 'Инг',
    region_eng: 'ING',
    region_rus: 'ИНГ',
    col: '6',
    row: '10',
  },
  {
    region: 'Республика Калмыкия',
    district: 'Южный федеральный округ',
    district_short: 'ЮФО',
    region_alt_rus: 'Калм',
    region_eng: 'KLM',
    region_rus: 'КАЛМ',
    col: '6',
    row: '8',
  },
  {
    region: 'Республика Карелия',
    district: 'Северо-Западный федеральный округ',
    district_short: 'СЗФО',
    region_alt_rus: 'Кар',
    region_eng: 'KRL',
    region_rus: 'КРЛ',
    col: '3',
    row: '1',
  },
  {
    region: 'Республика Коми',
    district: 'Северо-Западный федеральный округ',
    district_short: 'СЗФО',
    region_alt_rus: 'Коми',
    region_eng: 'KOM',
    region_rus: 'КОМИ',
    col: '9',
    row: '2',
  },
  {
    region: 'Республика Крым',
    district: 'Южный федеральный округ',
    district_short: 'ЮФО',
    region_alt_rus: 'Крым',
    region_eng: 'KRM',
    region_rus: 'КРЫМ',
    col: '2',
    row: '8',
  },
  {
    region: 'Республика Марий Эл',
    district: 'Приволжский федеральный округ',
    district_short: 'ПФО',
    region_alt_rus: 'Мари',
    region_eng: 'MAR',
    region_rus: 'МАР',
    col: '7',
    row: '3',
  },
  {
    region: 'Республика Мордовия',
    district: 'Приволжский федеральный округ',
    district_short: 'ПФО',
    region_alt_rus: 'Мор',
    region_eng: 'MOR',
    region_rus: 'МОРД',
    col: '6',
    row: '5',
  },
  {
    region: 'Республика Саха (Якутия)',
    district: 'Дальневосточный федеральный округ',
    district_short: 'ДФО',
    region_alt_rus: 'Саха',
    region_eng: 'SAH',
    region_rus: 'САХА',
    col: '15',
    row: '2',
  },
  {
    region: 'Республика Северная Осетия — Алания',
    district: 'Северо-Кавказский федеральный округ',
    district_short: 'СКФО',
    region_alt_rus: 'Осeт',
    region_eng: 'OSE',
    region_rus: 'ОСЕТ',
    col: '5',
    row: '10',
  },
  {
    region: 'Республика Татарстан',
    district: 'Приволжский федеральный округ',
    district_short: 'ПФО',
    region_alt_rus: 'Тат',
    region_eng: 'TAT',
    region_rus: 'ТАТ',
    col: '8',
    row: '4',
  },
  {
    region: 'Республика Тыва',
    district: 'Сибирский федеральный округ',
    district_short: 'СФО',
    region_alt_rus: 'Тыва',
    region_eng: 'TYV',
    region_rus: 'ТЫВА',
    col: '13',
    row: '5',
  },
  {
    region: 'Республика Хакасия',
    district: 'Сибирский федеральный округ',
    district_short: 'СФО',
    region_alt_rus: 'Хак',
    region_eng: 'HAK',
    region_rus: 'ХАК',
    col: '13',
    row: '4',
  },
  {
    region: 'Ростовская область',
    district: 'Южный федеральный округ',
    district_short: 'ЮФО',
    region_alt_rus: 'Рос',
    region_eng: 'RST',
    region_rus: 'РОСТ',
    col: '5',
    row: '8',
  },
  {
    region: 'Рязанская область',
    district: 'Центральный федеральный округ',
    district_short: 'ЦФО',
    region_alt_rus: 'Ряз',
    region_eng: 'RZN',
    region_rus: 'РЯЗН',
    col: '5',
    row: '5',
  },
  {
    region: 'Самарская область',
    district: 'Приволжский федеральный округ',
    district_short: 'ПФО',
    region_alt_rus: 'Сам',
    region_eng: 'SAM',
    region_rus: 'САМ',
    col: '8',
    row: '5',
  },
  {
    region: 'Санкт-Петербург',
    district: 'Северо-Западный федеральный округ',
    district_short: 'СЗФО',
    region_alt_rus: 'Спб',
    region_eng: 'SPB',
    region_rus: 'СПБ',
    col: '0',
    row: '0',
  },
  {
    region: 'Саратовская область',
    district: 'Приволжский федеральный округ',
    district_short: 'ПФО',
    region_alt_rus: 'Сар',
    region_eng: 'SAR',
    region_rus: 'САР',
    col: '7',
    row: '6',
  },
  {
    region: 'Сахалинская область',
    district: 'Дальневосточный федеральный округ',
    district_short: 'ДФО',
    region_alt_rus: 'Схлн',
    region_eng: 'SHL',
    region_rus: 'СХЛН',
    col: '18',
    row: '3',
  },
  {
    region: 'Cевастополь',
    district: 'Южный федеральный округ',
    district_short: 'ЮФО',
    region_alt_rus: 'Сев',
    region_eng: 'SEV',
    region_rus: 'СЕВ',
    col: '0',
    row: '8',
  },
  {
    region: 'Свердловская область',
    district: 'Уральский федеральный округ',
    district_short: 'УФО',
    region_alt_rus: 'Свер',
    region_eng: 'SVE',
    region_rus: 'СВРД',
    col: '10',
    row: '4',
  },
  {
    region: 'Смоленская область',
    district: 'Центральный федеральный округ',
    district_short: 'ЦФО',
    region_alt_rus: 'Смол',
    region_eng: 'SMO',
    region_rus: 'СМОЛ',
    col: '2',
    row: '4',
  },
  {
    region: 'Ставропольский край',
    district: 'Северо-Кавказский федеральный округ',
    district_short: 'СКФО',
    region_alt_rus: 'Став',
    region_eng: 'STV',
    region_rus: 'СТАВ',
    col: '5',
    row: '9',
  },
  {
    region: 'Тамбовская область',
    district: 'Центральный федеральный округ',
    district_short: 'ЦФО',
    region_alt_rus: 'Там',
    region_eng: 'TMB',
    region_rus: 'ТАМБ',
    col: '5',
    row: '6',
  },
  {
    region: 'Тверская область',
    district: 'Центральный федеральный округ',
    district_short: 'ЦФО',
    region_alt_rus: 'Твeр',
    region_eng: 'TVE',
    region_rus: 'ТВЕР',
    col: '3',
    row: '3',
  },
  {
    region: 'Томская область',
    district: 'Сибирский федеральный округ',
    district_short: 'СФО',
    region_alt_rus: 'Томск',
    region_eng: 'TOM',
    region_rus: 'ТОМ',
    col: '12',
    row: '3',
  },
  {
    region: 'Тульская область',
    district: 'Центральный федеральный округ',
    district_short: 'ЦФО',
    region_alt_rus: 'Тул',
    region_eng: 'TUL',
    region_rus: 'ТУЛ',
    col: '4',
    row: '5',
  },
  {
    region: 'Тюменская область',
    district: 'Уральский федеральный округ',
    district_short: 'УФО',
    region_alt_rus: 'Тюм',
    region_eng: 'TMN',
    region_rus: 'ТЮМ',
    col: '11',
    row: '3',
  },
  {
    region: 'Удмуртская Республика',
    district: 'Приволжский федеральный округ',
    district_short: 'ПФО',
    region_alt_rus: 'Удм',
    region_eng: 'UDM',
    region_rus: 'УДМ',
    col: '9',
    row: '4',
  },
  {
    region: 'Ульяновская область',
    district: 'Приволжский федеральный округ',
    district_short: 'ПФО',
    region_alt_rus: 'Уль',
    region_eng: 'ULN',
    region_rus: 'УЛЬН',
    col: '7',
    row: '5',
  },
  {
    region: 'Хабаровский край',
    district: 'Дальневосточный федеральный округ',
    district_short: 'ДФО',
    region_alt_rus: 'Хаб',
    region_eng: 'HAB',
    region_rus: 'ХАБ',
    col: '16',
    row: '3',
  },
  {
    region: 'Ханты-Мансийский автономный округ — Югра',
    district: 'Уральский федеральный округ',
    district_short: 'УФО',
    region_alt_rus: 'Хан',
    region_eng: 'HAN',
    region_rus: 'ХАН',
    col: '10',
    row: '3',
  },
  {
    region: 'Челябинская область',
    district: 'Уральский федеральный округ',
    district_short: 'УФО',
    region_alt_rus: 'Чел',
    region_eng: 'CHL',
    region_rus: 'ЧЕЛ',
    col: '10',
    row: '5',
  },
  {
    region: 'Чеченская Республика',
    district: 'Северо-Кавказский федеральный округ',
    district_short: 'СКФО',
    region_alt_rus: 'Чеч',
    region_eng: 'CEC',
    region_rus: 'ЧЕЧ',
    col: '6',
    row: '9',
  },
  {
    region: 'Чувашская Республика',
    district: 'Приволжский федеральный округ',
    district_short: 'ПФО',
    region_alt_rus: 'Чув',
    region_eng: 'CHV',
    region_rus: 'ЧУВ',
    col: '7',
    row: '4',
  },
  {
    region: 'Чукотский автономный округ',
    district: 'Дальневосточный федеральный округ',
    district_short: 'ДФО',
    region_alt_rus: 'Чук',
    region_eng: 'CHK',
    region_rus: 'ЧУК',
    col: '16',
    row: '1',
  },
  {
    region: 'Ямало-Ненецкий автономный округ',
    district: 'Уральский федеральный округ',
    district_short: 'УФО',
    region_alt_rus: 'Ямал',
    region_eng: 'YAM',
    region_rus: 'ЯМН',
    col: '10',
    row: '2',
  },
  {
    region: 'Ярославская область',
    district: 'Центральный федеральный округ',
    district_short: 'ЦФО',
    region_alt_rus: 'Яро',
    region_eng: 'YAR',
    region_rus: 'ЯРЛ',
    col: '4',
    row: '3',
  },
];
