#!/bin/bash

jq -Rsn '[inputs | . / "\n" | .[1:]
   | (.[] | select(length > 0) | . / ",") as $input
   | {"region": $input[0], "district": $input[1], "district_short": $input[2],
      "region_alt_rus": $input[3], "region_eng": $input[4], "region_rus": $input[5],
      "col": $input[6], "row": $input[7]}]' < data.csv